### ISSUE TITLE
Email tag filter isn't working

### ISSUE THREAD

**Issue by ramonmedeiros** [patchew-project/patchew#16] opened 2016-12-13 11:28 UTC
Hi,

Just found out that some patches from Kimchi are being listed at Wok: http://patchew.org/Wok/. I can fix this?

**Comment by famz** [comment] 2016-12-14 10:08
I still need to implement it :)

**Comment by bonzini** [comment] 2017-12-12 08:35
Duplicate of issue #5.

**Closed by bonzini** 2017-12-12 08:35 UTC
Labels: duplicate
